wallets.json
=> Update wallets.json with igrant.io

wallets/Procivis One Wallet.json, wallets/Procivis One.json, wallets/hightrust.id.json, wallets/iGrant.io Data Wallet.json, wallets/iGrant.io Enterprise Wallet.json
Fixed issues with recent wallet pull requests
=> Validity fixes

wallets/Procivis One Wallet.json, wallets/Procivis One.json, wallets/hightrust.id.json
some wallet json files have incorrect path to schema
=> fixed schema paths

viewer/pnpm-lock.yaml, viewer/src/app/wallets-add/wallets-add.component.ts, viewer/src/app/wallets.service.ts
=> Bug: Add missing fields to generation form

wallets/Hologram.json
Adding some more info about Hologram app, including link for Google Play Store.
=> Update info about Hologram

CONTRIBUTING.md, MAINTAINERS.md
=> add contributing file

viewer/scripts/newsletter.mjs
=> fix: newsletter production call

viewer/scripts/link-checker.mjs, viewer/src/app/wallets/wallets-show/wallets-show.component.html, viewer/src/app/wallets/wallets-show/wallets-show.component.ts, viewer/src/app/wallets/wallets.service.ts
=> show a warning on the wallet page if something is not loading

viewer/src/app/app.config.ts, viewer/src/app/wallets/wallets-list/wallets-list.component.html, viewer/src/app/wallets/wallets-list/wallets-list.component.ts, viewer/src/app/wallets/wallets-show/wallets-show.component.ts, viewer/src/app/wallets/wallets.service.ts
adds a warning to all wallets with missing entris
=> fix: print a warning to all wallet elements

viewer/src/app/app.component.ts, viewer/src/app/seo-resolver.ts, viewer/src/app/wallets/wallets.service.ts
=> fix: og image loading

.github/workflows/newsletter.yml
Add location and local vars to github newsletter action
=> optimize manual trigger

viewer/package-lock.json, viewer/package.json, viewer/scripts/mail-template.hbs, viewer/scripts/newsletter.mjs
=> use mailjet as provider

.github/workflows/newsletter.yml, viewer/src/app/case-studies/case-studies-list/case-studies-list.component.ts
=> add link to mailjet

viewer/scripts/newsletter.mjs
=> set new mail address

wallets/vidos-id.json
This PR adds Vidos.id Verifier details to wallets/vidos-id.json
Signed-off-by: Tim Boeckmann <2022378+tboeckmann@users.noreply.github.com>
=> add vidos-id.json

.github/workflows/main.yml
=> set correct context

viewer/package.json, viewer/src/app/wallets/wallets-data.ts
=> fix: add merge for ssr build

README.md, viewer/scripts/newsletter.mjs
=> update readme with a diagram

data/wallets/procivis-one-desk.json, data/wallets/procivis-one-verifier.json
Hi!
We provided wrong license entries for Desk and Verifier apps. So this Pull Request change it to Commercial
=> Update Procivis licenses for Desk and Verifier

data/wallets/altme.json, data/wallets/talao.json
Hello
Here are the new version of the json files for altme and talao wallets.
I havent updated wallets-data.ts. Do you have a script to do this or should I update manually?
=> Update altme and talao wallet providers properties

viewer/package.json
=> add remove script back again

viewer/src/app/case-studies/case-studies-list-embedded/case-studies-list-embedded.component.ts
fix double entries when a product from the same company is used.
=> fix: remove double companies

data/dependencies/eudi-wallet.json, data/wallets/swisssign-wallet.json
Hi 👋 
I would like to add the SwissSign Wallet to the wallets overview.
I also added a new dependency, the EUDI Wallet reference implementation. Feel free to update the name or the metadata.
Thank you !
=> Add swisssign wallet
